on:
  push:
    tags:
      - 'v*'

name: Deploy to Production

jobs:
  build-deploy-server:
    name: Deploy to Production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set env
        run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF#refs/*/}
      
      - name: GAE environment variable compiler
        uses: ikuanyshbekov/app-yaml-env-compiler@v1.1
        env:
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_BOT_API_KEY: ${{ secrets.TELEGRAM_BOT_API_KEY }}
          
      - name: Change version
        run: |
          sed -i app.yaml -e "s/__RELEASE__/$RELEASE_VERSION/"

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_key: ${{ secrets.APP_ENGINE_KEY}}

      - name: Deploy
        run: |
          gcloud --quiet app deploy app\.yaml --project ${{ secrets.PROJECT_ID }} --version $(echo $RELEASE_VERSION | sed "s/\./-/g") --no-promote
